{"name": "verify that user is able to click on notification settings button", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00F2ACD3+2075859]\n\tOrdinal0 [0x00EBEE61+1633889]\n\tOrdinal0 [0x00DBB7BD+571325]\n\tOrdinal0 [0x00DB7CD2+556242]\n\tOrdinal0 [0x00DAEC5D+519261]\n\tOrdinal0 [0x00DAFAEC+522988]\n\tOrdinal0 [0x00DAEF27+519975]\n\tOrdinal0 [0x00DAE2EB+516843]\n\tOrdinal0 [0x00DAE231+516657]\n\tOrdinal0 [0x00DAD0A3+512163]\n\tOrdinal0 [0x00DAD5AD+513453]\n\tOrdinal0 [0x00DBD0CE+577742]\n\tOrdinal0 [0x00E1BC7D+965757]\n\tOrdinal0 [0x00E0731C+881436]\n\tOrdinal0 [0x00E1B56A+963946]\n\tOrdinal0 [0x00E07136+880950]\n\tOrdinal0 [0x00DDFEFD+720637]\n\tOrdinal0 [0x00DE0F3F+724799]\n\tGetHandleVerifier [0x011DEED2+2769538]\n\tGetHandleVerifier [0x011D0D95+2711877]\n\tGetHandleVerifier [0x00FBA03A+521194]\n\tGetHandleVerifier [0x00FB8DA0+516432]\n\tOrdinal0 [0x00EC682C+1665068]\n\tOrdinal0 [0x00ECB128+1683752]\n\tOrdinal0 [0x00ECB215+1683989]\n\tOrdinal0 [0x00ED6484+1729668]\n\tBaseThreadInitThunk [0x76AD7BA9+25]\n\tRtlInitializeExceptionChain [0x7776BB3B+107]\n\tRtlClearBits [0x7776BABF+191]\n\n", "trace": "  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\step_defination.py\", line 10, in launch_browser\n    context.driver.get(\"https://www.facebook.com/\")\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 441, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Open the browser and enter the valid URL", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=107.0.5304.88)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00F2ACD3+2075859]\n\tOrdinal0 [0x00EBEE61+1633889]\n\tOrdinal0 [0x00DBB7BD+571325]\n\tOrdinal0 [0x00DB7CD2+556242]\n\tOrdinal0 [0x00DAEC5D+519261]\n\tOrdinal0 [0x00DAFAEC+522988]\n\tOrdinal0 [0x00DAEF27+519975]\n\tOrdinal0 [0x00DAE2EB+516843]\n\tOrdinal0 [0x00DAE231+516657]\n\tOrdinal0 [0x00DAD0A3+512163]\n\tOrdinal0 [0x00DAD5AD+513453]\n\tOrdinal0 [0x00DBD0CE+577742]\n\tOrdinal0 [0x00E1BC7D+965757]\n\tOrdinal0 [0x00E0731C+881436]\n\tOrdinal0 [0x00E1B56A+963946]\n\tOrdinal0 [0x00E07136+880950]\n\tOrdinal0 [0x00DDFEFD+720637]\n\tOrdinal0 [0x00DE0F3F+724799]\n\tGetHandleVerifier [0x011DEED2+2769538]\n\tGetHandleVerifier [0x011D0D95+2711877]\n\tGetHandleVerifier [0x00FBA03A+521194]\n\tGetHandleVerifier [0x00FB8DA0+516432]\n\tOrdinal0 [0x00EC682C+1665068]\n\tOrdinal0 [0x00ECB128+1683752]\n\tOrdinal0 [0x00ECB215+1683989]\n\tOrdinal0 [0x00ED6484+1729668]\n\tBaseThreadInitThunk [0x76AD7BA9+25]\n\tRtlInitializeExceptionChain [0x7776BB3B+107]\n\tRtlClearBits [0x7776BABF+191]\n\n", "trace": "  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\step_defination.py\", line 10, in launch_browser\n    context.driver.get(\"https://www.facebook.com/\")\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 441, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Trupti\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667622813238, "stop": 1667622814790}, {"name": "When Enter the Username\"jadhavsanjana1975@gmail.com \"", "status": "skipped", "start": 1667622814793, "stop": 1667622814793}, {"name": "And Enter the Password\"Cartoon#98\"", "status": "skipped", "start": 1667622814793, "stop": 1667622814793}, {"name": "And Click on login button open", "status": "skipped", "start": 1667622814793, "stop": 1667622814793}, {"name": "And Click on friends button open_3", "status": "skipped", "start": 1667622814793, "stop": 1667622814793}, {"name": "And Click on notification settings button", "status": "skipped", "start": 1667622814793, "stop": 1667622814793}, {"name": "Then Click on notification dot button", "status": "skipped", "start": 1667622814793, "stop": 1667622814793}], "start": 1667622813238, "stop": 1667622814793, "uuid": "8c5552ea-6e31-42ea-ace3-273602f1f92e", "historyId": "02b9b70a16681447f36f0a40eaedd641", "fullName": "Friends_Module: verify that user is able to click on notification settings button", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Friends_Module"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}